version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: demo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_demo
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d

  api:
    build: ./backend
    container_name: demo-api
    restart: always
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/rag_demo
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app         # mount only your FastAPI source
      - ./frontend/dist:/code/static    # serve Vue build

volumes:
  db_data:
