"""create models

Revision ID: ddea7c0f6557
Revises: 
Create Date: 2025-10-01 02:07:09.567452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddea7c0f6557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from geoalchemy2 import Geometry
from pgvector.sqlalchemy import Vector


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'public_comments',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('objectid', sa.Integer, nullable=False),
        sa.Column('identification_type', sa.String, nullable=True),
        sa.Column('category', sa.String, nullable=True),
        sa.Column('comment', sa.String, nullable=True),
        sa.Column('name', sa.String, nullable=True),
        sa.Column('email', sa.String, nullable=True),
        sa.Column('public_view', sa.String, nullable=True),
        sa.Column('scenario', sa.String, nullable=True),
        sa.Column('question', sa.String, nullable=True),
        sa.Column('creator', sa.String, nullable=True),
        sa.Column('date_created', sa.BigInteger, nullable=True),
        sa.Column('editor', sa.String, nullable=True),
        sa.Column('date_edited', sa.BigInteger, nullable=True),
        sa.Column('like', sa.Integer, nullable=True),
        sa.Column('dislike', sa.Integer, nullable=True),
        sa.Column('phone', sa.String, nullable=True),
        sa.Column('admin', sa.String, nullable=True),
        sa.Column('hear_about', sa.String, nullable=True),
        sa.Column('global_id', sa.String, nullable=True),
        sa.Column('map_id', sa.Integer, nullable=True),
        sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, spatial_index=True), nullable=False),
        sa.Column('embedding', Vector(1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pub',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
