name: Build and deploy presentation to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build presentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: presentation
        run: npm ci

      - name: Build
        working-directory: presentation
        run: npm run build

      - name: Ensure index.html exists (redirect fallback)
        run: |
          if [ ! -f presentation/dist/index.html ]; then
            mkdir -p presentation/dist
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./index.html"></head><body>Redirecting...</body></html>' > presentation/dist/index.html
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: presentation/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
